# Site title and subtitle. This is used in _includes/header.html
title: 'User guide for the MIMIC-II database'
subtitle: 'Exploring critical care data'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'http://mimic2.github.io/v3.0/'

# Default categories (in order) to appear in the navigation
sections: [
    ['bac', 'Background'],
    ['ins', 'Accessing MIMIC'],
    ['new','What's new in v3.0?'],
    ['code', 'Code'],
    ['dat', 'Database'],
#    ['doc', 'Documentation'],
#    ['tut', 'Tutorial'],
#    ['dev', 'Developers'],
#    ['post', 'Posts'],
    ['sum', 'Summary'],
    ['ref', 'Reference'],
    ['app', 'Appendix']
]

# Create new pages with: 
# ruby bin/jekyll-page "Some Page Title" ref

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/v3.0'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
