/*
  createdb_mysql.sql

  Created on   : 4 May 2015 by Tom Pollard
  Last updated :
     $Author: Tom Pollard$
     $Date: 4 May 2015$

Load MIMIC-II v3.0-b1 flat files into a MySQL database
*/

-- 1. CREATE THE DATABASE

CREATE DATABASE mimic2_v3_0_b1;

-- 2. CREATE THE TABLES
-- Mapping of datatypes:
-- http://docs.oracle.com/cd/E12151_01/doc.150/e12155/oracle_mysql_compared.htm#g1034154

USE mimic2_v3_0_b1;

CREATE TABLE IF NOT EXISTS additives (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  ICUSTAY_ID mediumint unsigned DEFAULT NULL,
  ORDERID integer unsigned DEFAULT NULL,
  ITEMID mediumint unsigned DEFAULT NULL,
  LABEL varchar DEFAULT NULL,
  IOITEMID mediumint unsigned DEFAULT NULL,
  IOITEMLABEL varchar DEFAULT NULL,
  CHARTTIME datetime DEFAULT NULL,
  STARTTIME datetime DEFAULT NULL,
  ENDTIME datetime DEFAULT NULL,
  ELEMID mediumint unsigned DEFAULT NULL,
  CGID int unsigned DEFAULT NULL,
  CUID int unsigned DEFAULT NULL,
  VALUE numeric signed DEFAULT NULL,
  UOM varchar(70) DEFAULT NULL,
  IOITEMVALUE numeric signed DEFAULT NULL,
  IOITEMUOM varchar(101) DEFAULT NULL,
  SOURCE_FLG varchar(10) DEFAULT NULL,
  ADDITIVESDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (ADDITIVESDATAID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS admissions (
  HADM_ID mediumint unsigned DEFAULT NULL,
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  ADMIT_DT
  ADMIT_TIME
  DISCH_DT
  DISCH_TIME
  ADM_DIAGNOSIS
  FIRST_SERVICE
  LAST_SERVICE
  ADMISSIONSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (HADM_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS censusevents (
  CENSUS_ID int(11) DEFAULT NULL,
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  ICUSTAY_ID mediumint unsigned DEFAULT NULL,
  INTIME
  OUTTIME
  CUID
  LOS
  DESTCAREUNIT
  DISCHSTATUS
  CENSUSEVENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chartevents (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  HADM_ID mediumint unsigned DEFAULT NULL,
  ICUSTAY_ID mediumint unsigned DEFAULT NULL,
  ITEMID
  LABEL
  TIME
  ELEMID
  VALIDATIONTIME
  CGID
  CUID
  VALUE1
  VALUE1NUM
  VALUE1UOM
  COMMENTS
  VALUE2
  VALUE2NUM
  VALUE2UOM
  RESULTSTATUS
  STOPPED
  WARNING
  ERROR
  xxxid integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cptevents (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  HADM_ID mediumint unsigned DEFAULT NULL,
  CPT_CD
  CPTEVENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS d_caregivers (
  CGID mediumint unsigned DEFAULT NULL,
  CG_UNIQUEID mediumint unsigned DEFAULT NULL,
  LABEL
  DESCRIPTION
  CGID_STATUS
  D_CAREGIVERSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS d_careunits (
  CUID mediumint unsigned DEFAULT NULL,
  LABEL
  D_CAREUNITSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS d_items (
  ITEMID mediumint unsigned DEFAULT NULL,
  LABEL
  ABBREVIATION
  ORIGIN
  CODE
  CATEGORY
  UNITID
  UNITNAME
  TYPE
  DESCRIPTION
  LOWNORMALVALUE
  HIGHNORMALVALUE
  ALLERGYACTION
  LOINC_CODE
  LOINC_DESCRIPTION
  OLD_LABITEMID
  OLD_TEST_NAME
  OLD_LOINC_CODE
  D_ITEMSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS d_patients (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  SEX
  DOB
  DOD
  HOSPITAL_EXPIRE_FLG
  ZIPCODE
  D_PATIENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS d_units (
  UNITID mediumint unsigned DEFAULT NULL,
  UNITNAME
  MULTIPLIER
  ADDITION
  ISBASEUNIT
  ISRELATIONAL
  ISTIME
  ISVOLUME
  CATEGORY
  D_UNITSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS demographic_detail (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  HADM_ID mediumint unsigned DEFAULT NULL,
  MARITAL_STATUS_ITEMID
  MARITAL_STATUS_DESCR
  ETHNICITY_ITEMID
  ETHNICITY_DESCR
  OVERALL_PAYOR_GROUP_ITEMID
  OVERALL_PAYOR_GROUP_DESCR
  RELIGON_ITEMID
  RELIGON_DESCR
  ADMISSION_TYPE_ITEMID
  ADMISSION_TYPE_DESCR
  ADMISSION_SOURCE_ITEMID
  ADMISSION_SOURCE_DESCR
  DEMOGRAPHIC_DETAILDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS drgevents (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  ITEMID mediumint unsigned DEFAULT NULL,
  TYPE
  CODE
  DESCRIPTION
  COST_WEIGHT
  DRGEVENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS icd9 (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  HADM_ID mediumint unsigned DEFAULT NULL,
  SEQUENCE
  CODE
  DESCRIPTION
  ICD9DATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS icustaydays (
  ICUSTAY_ID mediumint unsigned DEFAULT NULL,
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  SEQ
  BEGINTIME
  ENDTIME
  FIRST_DAY_FLG
  LAST_DAY_FLG
  ICUSTAYDAYSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS icustayevents (
  ICUSTAY_ID mediumint unsigned DEFAULT NULL,
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  INTIME
  OUTTIME
  LOS
  FIRST_CAREUNIT
  LAST_CAREUNIT
  ADMISSIONSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (ICUSTAY_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ioevents (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  ICUSTAY_ID mediumint unsigned DEFAULT NULL,
  ORDERID mediumint unsigned DEFAULT NULL,
  ITEMID mediumint unsigned DEFAULT NULL,
  LABEL
  CHARTTIME
  ELEMID mediumint unsigned DEFAULT NULL,
  ALTID
  REALTIME
  STARTTIME
  ENDTIME
  CGID mediumint unsigned DEFAULT NULL,
  CUID mediumint unsigned DEFAULT NULL,
  VALUE
  UOM
  UNITSHUNG
  UNITSHUNGUOM
  NEWBOTTLE
  STOPPED
  ESTIMATE
  IOEVENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS labevents (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  HADM_ID mediumint unsigned DEFAULT NULL,
  ITEMID mediumint unsigned DEFAULT NULL,
  CHARTTIME
  TEST_NAME
  VALUE
  VALUENUM
  VALUEUOM
  FLAG
  FLUID
  CATEGORY
  LOINC_CODE
  LABEVENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS medevents (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  ICUSTAY_ID mediumint unsigned DEFAULT NULL,
  ORDERID mediumint unsigned DEFAULT NULL,
  ITEMID mediumint unsigned DEFAULT NULL,
  LABEL
  SOLITEMID
  SOLITEMLABEL
  CHARTTIME
  ELEMID
  REALTIME
  STARTTIME
  ENDTIME
  VALUE
  UOM
  SOLITEMVALUE
  SOLITEMUOM
  CGID
  CUID
  STOPPED
  MEDEVENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS microbiologyevents (
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  HADM_ID mediumint unsigned DEFAULT NULL,
  TIME
  SPEC_TYPE_CD
  SPEC_ITEMID
  SPEC_TYPE_DESC
  ORG_CD
  ORG_ITEMID
  ORG_NAME
  ISOLATE_NUM
  AB_CD
  AB_ITEMID
  AB_NAME
  DILUTION_AMOUNT
  DILUTION_COMPARISON
  INTERPRETATION
  MICROBIOLOGYEVENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS noteevents (
  REC_ID mediumint unsigned DEFAULT NULL,
  SUBJECT_ID mediumint unsigned DEFAULT NULL,
  HADM_ID mediumint unsigned DEFAULT NULL,
  ICUSTAY_ID mediumint unsigned DEFAULT NULL,
  ELEM_ID mediumint unsigned DEFAULT NULL,
  CHARTTIME
  REALTIME
  CGID
  CORRECTION
  CUID
  CATEGORY
  TITLE
  TEXT
  EXAM_NAME
  PATIENT_INFO
  NOTEEVENTSDATAID integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orderentry (
  XXX int(11) DEFAULT NULL,
  xxxid integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS poe_med_order (
  XXX int(11) DEFAULT NULL,
  xxxid integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS procedureevents (
  XXX int(11) DEFAULT NULL,
  xxxid integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS totalbalevents (
  XXX int(11) DEFAULT NULL,
  xxxid integer NOT NULL UNIQUE,
  PRIMARY KEY (XXX)
) ENGINE=InnoDB;

-- 3. IMPORT THE TABLES

LOAD DATA LOCAL INFILE '/path/to/file.txt' 
INTO TABLE additives



