/******************************
**
** File: v30_MORTALITY.sql   
** Desc: Create a table containing different mortality cohorts.
** Auth: Franck Dernoncourt <francky@mit.edu>
** Date: 2015-07-18
** Impl: Uses MIMIC2V30.ADMISSIONS and MIMIC2V30.D_PATIENTS.
**       Each row represents one hospital stay.
** Time: 5 seconds on Tesla.
**
**************************
** Change History
**************************
** PR   Date	     Author           Description	
** --   --------   --------------   ------------------------------------
** 
*******************************/

DROP TABLE MORTALITY;

CREATE TABLE MORTALITY (
"HADM_ID" NUMBER(7,0), 
"SUBJECT_ID" NUMBER(7,0), 
"HOSP_STAY_DURATION_IN_DAYS" NUMBER, 
"NUM_OF_DAYS_ALIVE_FROM_ADMIT" NUMBER, 
"NUM_OF_DAYS_ALIVE_FROM_DISCH" NUMBER, 
"DIED_IN_HOSPITAL" CHAR CHECK ("DIED_IN_HOSPITAL" IN ('N','Y')), 
"DIED_DURING_THIS_HOSP_STAY" CHAR CHECK ("DIED_DURING_THIS_HOSP_STAY" IN ('N','Y')), -- 
"DIED_WITHIN_30D_FROM_ADMIT" CHAR CHECK ("DIED_WITHIN_30D_FROM_ADMIT" IN ('N','Y')),
"DIED_BT_30_AND_365D_FROM_ADMIT"  CHAR CHECK ("DIED_BT_30_AND_365D_FROM_ADMIT" IN ('N','Y')),
"ALIVE_AFTER_365D_FROM_ADMIT"  CHAR CHECK ("ALIVE_AFTER_365D_FROM_ADMIT" IN ('N','Y')),
"DIED_WITHIN_30D_FROM_DISCH" CHAR CHECK ("DIED_WITHIN_30D_FROM_DISCH" IN ('N','Y')),
"DIED_BT_30_AND_365D_FROM_DISCH"  CHAR CHECK ("DIED_BT_30_AND_365D_FROM_DISCH" IN ('N','Y')),
"ALIVE_AFTER_365D_FROM_DISCH"  CHAR CHECK ("ALIVE_AFTER_365D_FROM_DISCH" IN ('N','Y')),
"STILL_ALIVE" CHAR CHECK ("STILL_ALIVE" IN ('N','Y'))
);

COMMENT ON COLUMN MORTALITY.HADM_ID IS 'Hospital admission ID.';
COMMENT ON COLUMN MORTALITY.SUBJECT_ID IS 'Patient ID.';
COMMENT ON COLUMN MORTALITY.HOSP_STAY_DURATION_IN_DAYS IS 'The duration of the patient''s hospital stay expressed in days.';
COMMENT ON COLUMN MORTALITY.NUM_OF_DAYS_ALIVE_FROM_ADMIT IS 'How many days the patient live, right after hospital admission. If NULL, the patient is still alive.';
COMMENT ON COLUMN MORTALITY.NUM_OF_DAYS_ALIVE_FROM_DISCH IS 'How many days the patient live, right after hospital discharge. If NULL, the patient is still alive.';
COMMENT ON COLUMN MORTALITY.DIED_IN_HOSPITAL IS 'Whether the patient died in the hospital, either during this hospital stay or another one (Y or N).';
COMMENT ON COLUMN MORTALITY.DIED_DURING_THIS_HOSP_STAY IS 'Whether the patient died in this hospital stay (Y or N).';
COMMENT ON COLUMN MORTALITY.DIED_WITHIN_30D_FROM_ADMIT IS 'Whether the patient died within 30 days after the hospital admission (Y or N).';
COMMENT ON COLUMN MORTALITY.DIED_BT_30_AND_365D_FROM_ADMIT IS 'Whether the patient died between 30 days and 365 days after the hospital admission (Y or N).';
COMMENT ON COLUMN MORTALITY.ALIVE_AFTER_365D_FROM_ADMIT IS 'Whether the patient was alive after 365 days after the hospital admission (Y or N).';
COMMENT ON COLUMN MORTALITY.DIED_WITHIN_30D_FROM_DISCH IS 'Whether the patient died within 30 days after the hospital discharge (Y or N).';
COMMENT ON COLUMN MORTALITY.DIED_BT_30_AND_365D_FROM_DISCH IS 'Whether the patient died between 30 days and 365 days after the hospital discharge (Y or N).';
COMMENT ON COLUMN MORTALITY.ALIVE_AFTER_365D_FROM_DISCH IS 'Whether the patient was alive after 365 days after the hospital discharge (Y or N).';
COMMENT ON COLUMN MORTALITY.STILL_ALIVE IS 'Whether the patient is still alive (Y or N).'; 
COMMENT ON TABLE MORTALITY IS 'The 3 columns DIED_WITHIN_30D_FROM_ADMIT, DIED_BT_30_AND_365D_FROM_ADMIT, and ALIVE_AFTER_365D_FROM_ADMIT are mutually exclusive. The 3 columns DIED_WITHIN_30D_FROM_DISCH, DIED_BT_30_AND_365D_FROM_DISCH, and ALIVE_AFTER_365D_FROM_DISCH are mutually exclusive.';


INSERT INTO MORTALITY (HADM_ID, SUBJECT_ID, HOSP_STAY_DURATION_IN_DAYS, NUM_OF_DAYS_ALIVE_FROM_ADMIT, NUM_OF_DAYS_ALIVE_FROM_DISCH, 
                         DIED_IN_HOSPITAL, DIED_DURING_THIS_HOSP_STAY, DIED_WITHIN_30D_FROM_ADMIT, DIED_BT_30_AND_365D_FROM_ADMIT,
                         ALIVE_AFTER_365D_FROM_ADMIT, DIED_WITHIN_30D_FROM_DISCH, DIED_BT_30_AND_365D_FROM_DISCH, ALIVE_AFTER_365D_FROM_DISCH, STILL_ALIVE)
                                     
SELECT ADMISSIONS.HADM_ID, ADMISSIONS.SUBJECT_ID, 
ROUND(CAST(ADMISSIONS.DISCH_DT AS DATE) - CAST(ADMISSIONS.ADMIT_DT AS DATE), 5) AS HOSP_STAY_DURATION_IN_DAYS,
ROUND(CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.ADMIT_DT AS DATE), 5) AS NUM_OF_DAYS_ALIVE_FROM_ADMIT,
ROUND(CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.DISCH_DT AS DATE), 5) AS NUM_OF_DAYS_ALIVE_FROM_DISCH,
CASE
    WHEN D_PATIENTS.HOSPITAL_EXPIRE_FLG = 'Y' THEN 'Y'
    ELSE 'N'
END AS DIED_IN_HOSPITAL,
CASE
    WHEN CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.DISCH_DT AS DATE) <= 0 THEN 'Y'
    ELSE 'N'
END AS DIED_DURING_THIS_HOSP_STAY,
CASE
    WHEN CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.ADMIT_DT AS DATE) <= 30  THEN 'Y'
    ELSE 'N'
END AS DIED_WITHIN_30D_FROM_ADMIT,
CASE
    WHEN CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.ADMIT_DT AS DATE) > 30 AND CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.ADMIT_DT AS DATE) <= 365  THEN 'Y'
    ELSE 'N'
END AS DIED_BT_30_AND_365D_FROM_ADMIT,
CASE
    WHEN (CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.ADMIT_DT AS DATE) > 365)  OR (D_PATIENTS.DOD IS NULL) THEN 'Y'
    ELSE 'N'
END AS ALIVE_AFTER_365D_FROM_ADMIT,
CASE
    WHEN CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.DISCH_DT AS DATE) <= 30  THEN 'Y'
    ELSE 'N'
END AS DIED_WITHIN_30D_FROM_DISCH,
CASE
    WHEN CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.DISCH_DT AS DATE) > 30 AND CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.DISCH_DT AS DATE) <= 365  THEN 'Y'
    ELSE 'N'
END AS DIED_BT_30_AND_365D_FROM_DISCH,
CASE
    WHEN (CAST(D_PATIENTS.DOD AS DATE) - CAST(ADMISSIONS.DISCH_DT AS DATE) > 365) OR (D_PATIENTS.DOD IS NULL) THEN 'Y'
    ELSE 'N'
END AS ALIVE_AFTER_365D_FROM_DISCH,
CASE
    WHEN D_PATIENTS.DOD IS NULL THEN 'Y'
    ELSE 'N'
END AS STILL_ALIVE

FROM MIMIC2V30.ADMISSIONS, MIMIC2V30.D_PATIENTS 
WHERE ADMISSIONS.SUBJECT_ID = D_PATIENTS.SUBJECT_ID
ORDER BY ADMISSIONS.HADM_ID ASC;
  
COMMIT;
